### ISSUE TITLE
8 command generate an error

### ISSUE THREAD

**Issue by vinayakumarr** [mayank93/Twitter-Sentiment-Analysis#1]
I am able to execute all commands but python ./code/findf1.py ./code/taskB.gs ./code/taskB.pred generates an error

**Comment by ayushidalmia** [comment]
Can you tell more about the error, maybe copy paste it? What is the error?

**Comment by vinayakumarr** [comment]
it should be findF1.py, your code giving 59 percentage accuracy. I would like is this constant or any method to improve this. I have local language kannada data set and how to make it work for kannada data set.

**Comment by ayushidalmia** [comment]
Currently it only supports English language. You need to build your own tokeniser and dictionary for kannada.
